# Laundry Room Doorbell
- alias: '[DOORBELL] Laundry Room'
  
  trigger:
    - platform: state
      entity_id: sensor.laundry_room_doorbell_action
      to: 'single'
      
    - platform: state
      entity_id: sensor.laundry_room_doorbell_action
      to: 'double'
      
    - platform: state
      entity_id: sensor.laundry_room_doorbell_action
      to: 'hold'
      
  action:
    - service: notify.pushover
      data:
        message: Doorbell at Laundry Room just got pushed
        title: Doorbell pushed
            
    - service: media_player.play_media
      data:
        media_content_id: /local/sounds/doorbell.mp3
        media_content_type: music
      target:
        entity_id: media_player.bedroom_clock
        
    - service: media_player.play_media
      data:
        media_content_id: /local/sounds/doorbell.mp3
        media_content_type: music
      target:
        entity_id: media_player.office_speaker
        
    - service: media_player.play_media
      data:
        media_content_id: /local/sounds/doorbell.mp3
        media_content_type: music
      target:
        entity_id: media_player.living_room_speaker
        
    - service: media_player.play_media
      data:
        media_content_id: /local/sounds/doorbell.mp3
        media_content_type: music
      target:
        entity_id: media_player.kitchen_display