# Update Notification
- alias: '[HOMEASSISTANT] Update notification'

  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      from: 'off'
      to: 'on'
      
  action:
    - service: notify.pushover
      data:
        title: New release available
        message: There is a new Home Assistant release available.