# Trigger alarm when sensor is triggered and alarm is armed
- alias: '[SECURITY] Home Monitoring - Trigger when armed'
  
  trigger:
    - platform: state
      entity_id: group.alarmsystem_sensors
      to: 'on'
      
  condition:
    - condition: template
      value_template: "{{ not is_state('alarm_control_panel.home_monitoring', 'disarmed') }}"
  
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.home_monitoring
        
    - service: light.turn_on
      entity_id: group.alarmsystem_lights
      
    - service: media_player.volume_set
      data:
        entity_id: group.notification_speakers
        volume_level: 1
        
    - repeat:
        while: "{{ is_state('alarm_control_panel.home_monitoring', 'triggered') and repeat.index < 15 }}"
        sequence:
          - service: media_player.play_media
            data:
              entity_id: group.notification_speakers
              media_content_id: /local/sounds/intruder.mp3
              media_content_type: music
          - delay:
              seconds: 15
              
# Disarm by webhook
- alias: '[SECURITY] Disarm alarm by webhook'

  trigger:
    - platform: webhook
      webhook_id: !secret webhook_disarm_id
      
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_monitoring
      state: 'triggered'
  
  action:
    - service: media_player.media_stop
      entity_id: group.notification_speakers
    
    - service: light.turn_off
      entity_id: group.alarmsystem_lights
      
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.home_monitoring
    
    - service: notify.pushover
      data:
        message: Alarm aborted and disarmed by webhook
        title: Intruder Alarm aborted