# Trigger alarm when sensor is triggered and alarm is armed (home/night)
- alias: '[SECURITY] Home Monitoring - Trigger when armed (home/night)'
  
  trigger:
    - platform: state
      entity_id: group.alarmsystem_sensors_home
      to: 'on'
      
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.home_monitoring
          state: 'armed_home'
        
        - condition: state
          entity_id: alarm_control_panel.home_monitoring
          state: 'armed_night'
  
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.home_monitoring
        
    - service: light.turn_on
      entity_id: group.alarmsystem_lights
        
    - repeat:
        while: "{{ is_state('alarm_control_panel.home_monitoring', 'triggered') and repeat.index < 15 }}"
        sequence:
          - service: script.play_mp3_group
            data:
              entities:
                - media_player.bedroom_clock
                - media_player.office_speaker
                - media_player.living_room_speaker
                - media_player.kitchen_display
              file: /local/sounds/intruder.mp3
              volume: 1

          - delay:
              seconds: 15
              
# Trigger alarm when sensor is triggered and alarm is armed (away)
- alias: '[SECURITY] Home Monitoring - Trigger when armed (away)'
  
  trigger:
    - platform: state
      entity_id: group.alarmsystem_sensors_away
      to: 'on'
      
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_monitoring
      state: 'armed_away'
  
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.home_monitoring
        
    - service: light.turn_on
      entity_id: group.alarmsystem_lights
        
    - repeat:
        while: "{{ is_state('alarm_control_panel.home_monitoring', 'triggered') and repeat.index < 15 }}"
        sequence:
          - service: script.play_mp3_group
            data:
              entities:
                - media_player.bedroom_clock
                - media_player.office_speaker
                - media_player.living_room_speaker
                - media_player.kitchen_display
              file: /local/sounds/intruder.mp3
              volume: 1
              
          - delay:
              seconds: 15
              
# Disarm by webhook
- alias: '[SECURITY] Disarm alarm by webhook'

  trigger:
    - platform: webhook
      webhook_id: !secret webhook_disarm_id
      
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_monitoring
      state: 'triggered'
  
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.home_monitoring
    
    - service: light.turn_off
      entity_id: group.alarmsystem_lights
    
    - service: notify.pushover
      data:
        message: Alarm aborted and disarmed by webhook
        title: Intruder Alarm aborted