# Trigger alarm when sensor is triggered and alarm is armed (home/night)
- alias: '[SECURITY] Home Monitoring - Trigger when armed (home/night)'
  
  trigger:
    - platform: state
      entity_id: group.alarmsystem_sensors_home
      to: 'on'
      
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.home_monitoring
          state: 'armed_home'
        
        - condition: state
          entity_id: alarm_control_panel.home_monitoring
          state: 'armed_night'
  
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.home_monitoring
        
    - service: light.turn_on
      entity_id: group.alarmsystem_lights
      
    - service: media_player.volume_set
      data:
        volume_level: 1
      target:
        entity_id: group.notification_speakers
        
    - repeat:
        while: "{{ is_state('alarm_control_panel.home_monitoring', 'triggered') and repeat.index < 15 }}"
        sequence:
          - service: media_player.play_media
            data:
              media_content_id: /local/sounds/intruder.mp3
              media_content_type: music
            target:
              entity_id: media_player.bedroom_clock
              
          - service: media_player.play_media
            data:
              media_content_id: /local/sounds/intruder.mp3
              media_content_type: music
            target:
              entity_id: media_player.office_speaker
              
          - service: media_player.play_media
            data:
              media_content_id: /local/sounds/intruder.mp3
              media_content_type: music
            target:
              entity_id: media_player.living_room_speaker
              
          - service: media_player.play_media
            data:
              media_content_id: /local/sounds/intruder.mp3
              media_content_type: music
            target:
              entity_id: media_player.kitchen_display

          - delay:
              seconds: 15
              
# Trigger alarm when sensor is triggered and alarm is armed (away)
- alias: '[SECURITY] Home Monitoring - Trigger when armed (away)'
  
  trigger:
    - platform: state
      entity_id: group.alarmsystem_sensors_away
      to: 'on'
      
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_monitoring
      state: 'armed_away'
  
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.home_monitoring
        
    - service: light.turn_on
      entity_id: group.alarmsystem_lights
      
    - service: media_player.volume_set
      data:
        volume_level: 1
      target:
        entity_id: group.notification_speakers
        
    - repeat:
        while: "{{ is_state('alarm_control_panel.home_monitoring', 'triggered') and repeat.index < 15 }}"
        sequence:
          - service: media_player.play_media
            data:
              media_content_id: /local/sounds/intruder.mp3
              media_content_type: music
            target:
              entity_id: media_player.bedroom_clock
              
          - service: media_player.play_media
            data:
              media_content_id: /local/sounds/intruder.mp3
              media_content_type: music
            target:
              entity_id: media_player.office_speaker
              
          - service: media_player.play_media
            data:
              media_content_id: /local/sounds/intruder.mp3
              media_content_type: music
            target:
              entity_id: media_player.living_room_speaker
              
          - service: media_player.play_media
            data:
              media_content_id: /local/sounds/intruder.mp3
              media_content_type: music
            target:
              entity_id: media_player.kitchen_display
              
          - delay:
              seconds: 15
              
# Disarm by webhook
- alias: '[SECURITY] Disarm alarm by webhook'

  trigger:
    - platform: webhook
      webhook_id: !secret webhook_disarm_id
      
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_monitoring
      state: 'triggered'
  
  action:
    - service: media_player.media_stop
      target:
        entity_id: media_player.bedroom_clock
        
    - service: media_player.media_stop
      target:
        entity_id: media_player.office_speaker
        
    - service: media_player.media_stop
      target:
        entity_id: media_player.living_room_speaker
        
    - service: media_player.media_stop
      target:
        entity_id: media_player.kitchen_display
    
    - service: light.turn_off
      entity_id: group.alarmsystem_lights
      
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.home_monitoring
    
    - service: notify.pushover
      data:
        message: Alarm aborted and disarmed by webhook
        title: Intruder Alarm aborted