# Notify via Pushover and run scene if Location Mode changes
- alias: '[SECURITY] Location Mode'
  
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_monitoring
      to:
        - disarmed
        - armed_home
        - armed_away
        - armed_night

  action:
    - service: scene.turn_on
      data:
        entity_id: |
          {% if trigger.to_state.state == 'disarmed' %}
            scene.home
          {% else %}
            {% if trigger.to_state.state == 'armed_away' %}
              scene.away
            {% else %}
              scene.night
            {% endif %}
          {% endif %}
    
    - service: notify.pushover
      data:
        message: |
          {% if trigger.to_state.state == 'disarmed' %}
            Home Monitoring is now disarmed
          {% else %}
            {% if trigger.to_state.state == 'armed_away' %}
              Home Monitoring is now armed (away)
            {% else %}
              Home Monitoring is now armed (night)
            {% endif %}
          {% endif %}
        title: |
          {% if trigger.to_state.state == 'disarmed' %}
            Home disarmed
          {% else %}
            Home armed
          {% endif %}
          
    - service: media_player.volume_set
      data:
        volume_level: |
          {% if trigger.to_state.state == 'disarmed' %}
            0.6
          {% else %}
            {% if trigger.to_state.state == 'armed_away' %}
              1
            {% else %}
              0.5
            {% endif %}
          {% endif %}
      target:
        entity_id: media_player.bedroom_clock
        
    - service: media_player.volume_set
      data:
        volume_level: |
          {% if trigger.to_state.state == 'disarmed' %}
            0.6
          {% else %}
            {% if trigger.to_state.state == 'armed_away' %}
              1
            {% else %}
              0.5
            {% endif %}
          {% endif %}
      target:
        entity_id: media_player.office_speaker
        
    - service: media_player.volume_set
      data:
        volume_level: |
          {% if trigger.to_state.state == 'disarmed' %}
            0.6
          {% else %}
            {% if trigger.to_state.state == 'armed_away' %}
              1
            {% else %}
              0.5
            {% endif %}
          {% endif %}
      target:
        entity_id: media_player.living_room_speaker
        
    - service: media_player.volume_set
      data:
        volume_level: |
          {% if trigger.to_state.state == 'disarmed' %}
            0.6
          {% else %}
            {% if trigger.to_state.state == 'armed_away' %}
              1
            {% else %}
              0.5
            {% endif %}
          {% endif %}
      target:
        entity_id: media_player.kitchen_display