# Toggle Location Mode based on Presence Sensor
- alias: '[SECURITY] Presence Sensor'
  
  trigger:
    - platform: state
      entity_id: person.jonas_laeborg
      to: home
      
    - platform: state
      entity_id: person.jonas_laeborg
      from: home
      
    - platform: state
      entity_id: person.jannie_kaul_jorgensen
      to: home
      
    - platform: state
      entity_id: person.jannie_kaul_jorgensen
      from: home
  
  action:
    - service: |
        {% if trigger.to_state.state == 'home' %}
          alarm_control_panel.alarm_disarm
        {% else %}
          {% if states.alarm_control_panel.home_monitoring.state == 'armed_night' %}
            {% if states.person | selectattr('state','eq','home') | list | count > 0 %}
              alarm_control_panel.alarm_arm_night
            {% else %}
              alarm_control_panel.alarm_arm_away
            {% endif %}
          {% else %}
            {% if states.person | selectattr('state','eq','home') | list | count > 0 %}
              alarm_control_panel.alarm_disarm
            {% else %}
              alarm_control_panel.alarm_arm_away
            {% endif %}
          {% endif %}
        {% endif %}
      entity_id: alarm_control_panel.home_monitoring