aspect_ratio: 1/1
show_state: true
show_icon: true
state:
  - value: 'on'
    styles:
      icon:
        - color: '#cdcdcd'
      card:
        - background-color: 'rgba(0, 0, 0, .6)'
        - color: '#cdcdcd'
styles:
  img_cell:
    - position: absolute
    - top: 10px
    - left: 10px
    - width: 50px
    - height: 50px
  icon:
    - position: relative
    - top: auto
    - left: auto
    - color: '#5b5b5b'
    - margin: 0px
    - height: 50px
    - max-width: 50px
    - width: auto
  name:
    - position: absolute
    - bottom: 30px
    - left: 10px
  state:
    - position: absolute
    - bottom: 10px
    - left: 10px
    - font-size: 15px
  card:
    - font-weight: normal
    - font-size: 17px
    - background-color: 'rgba(0, 0, 0, .2)'
    - border: '1px solid #1b1b1b'
    - box-shadow: none
    - transition: none
    - border-radius: 0px
    - color: '#5b5b5b'
  custom_fields:
    circle:
      - position: absolute
      - top: 5px
      - right: 5px
      - width: 50px