aspect_ratio: 1/1
show_state: true
show_icon: true
state:
  - value: 'on'
    styles:
      icon:
        - color: '#cdcdcd'
      card:
        - background-color: 'rgba(0, 0, 0, .6)'
        - color: '#cdcdcd'
styles:
  img_cell:
    - position: absolute
    - top: 5%
    - left: 10%
  icon:
    - position: absolute
    - top: 0
    - left: 0
    - width: 50px
    - height: 50px
    - color: '#5b5b5b'
    - text-align: left
    - vertical-align: top
  name:
    - position: absolute
    - bottom: 22%
    - left: 10%
  state:
    - position: absolute
    - bottom: 8%
    - left: 10%
    - font-size: 15px
  card:
    - font-weight: normal
    - font-size: 17px
    - background-color: 'rgba(0, 0, 0, .2)'
    - border: '1px solid #1b1b1b'
    - box-shadow: none
    - transition: none
    - border-radius: 0px
    - color: '#5b5b5b'
  custom_fields:
    circle:
      - position: absolute
      - top: 5%
      - right: 5%
      - width: 50px