# Sleep Timer - Start Timer
- alias: '[ELECTRONIC] Sleep Timer for Bedroom TV - Start Timer'

  trigger:
    - platform: state
      entity_id: media_player.bedroom_tv
      to: 'on'
      
    - platform: state
      entity_id: alarm_control_panel.home_monitoring
      to: 'armed_night'
      
  condition:
    - condition: state
      entity_id: media_player.bedroom_tv
      state: 'on'
      
    - condition: state
      entity_id: alarm_control_panel.home_monitoring
      state: 'armed_night'
      
  action:
    - service: timer.start
      entity_id: timer.bedroom_tv
      
# Sleep Timer - Cancel Timer
- alias: '[ELECTRONIC] Sleep Timer for Bedroom TV - Cancel Timer'
  
  trigger:
    - platform: state
      entity_id: media_player.bedroom_tv
      to: 'off'
      
    - platform: state
      entity_id: alarm_control_panel.home_monitoring
      from: 'armed_night'
  
  condition:
    - condition: state
      entity_id: timer.bedroom_tv
      state: 'active'
    
  action:
    - service: timer.cancel
      entity_id: timer.bedroom_tv
      
# Sleep Timer - Reload Timer
- alias: '[ELECTRONIC] Sleep Timer for Bedroom TV - Reload Timer'
  
  trigger:
    - platform: state
      entity_id: media_player.bedroom_tv
      attribute: source
    
    - platform: state
      entity_id: media_player.bedroom_tv
      attribute: media_channel
    
    - platform: state
      entity_id: media_player.bedroom_tv
      attribute: volume_level
    
    - platform: state
      entity_id: media_player.bedroom_tv
      attribute: is_volume_muted
      
  condition:
    - condition: state
      entity_id: media_player.bedroom_tv
      state: 'on'
      for:
        seconds: 30
      
    - condition: state
      entity_id: alarm_control_panel.home_monitoring
      state: 'armed_night'
      
    - condition: state
      entity_id: timer.bedroom_tv
      state: 'active'
    
  action:
    - service: timer.cancel
      entity_id: timer.bedroom_tv
      
    - service: timer.start
      entity_id: timer.bedroom_tv
      
# Sleep Timer - Warning
- alias: '[ELECTRONIC] Sleep Timer for Bedroom TV - Warning'
  
  trigger:
    - platform: template
      value_template: >
        {% set hours = state_attr('timer.bedroom_tv', 'duration').split(':')[0] %}
        {% set minutes = state_attr('timer.bedroom_tv', 'duration').split(':')[1] %}
        {% set seconds = state_attr('timer.bedroom_tv', 'duration').split(':')[2] %}
        {% set total = (hours | int * 60 * 60) + (minutes | int * 60) + (seconds | int) %}
        
        {{ as_timestamp(states.timer.bedroom_tv.last_changed) - now().timestamp() > total - 300 }}
      
  condition:
    - condition: state
      entity_id: media_player.bedroom_tv
      state: 'on'
      
    - condition: state
      entity_id: alarm_control_panel.home_monitoring
      state: 'armed_night'
      
    - condition: state
      entity_id: timer.bedroom_tv
      state: 'active'
      for:
        minutes: 1
    
  action:
    - service: tts.google_translate_say
      data:
        message: Bedroom TV will Turn Off in 5 minutes
      target:
        entity_id: media_player.bedroom_clock
        
# Sleep Timer - Turn Off
- alias: '[ELECTRONIC] Sleep Timer for Bedroom TV - Turn Off'
  
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.bedroom_tv
      
  condition:
    - condition: state
      entity_id: media_player.bedroom_tv
      state: 'on'
      
    - condition: state
      entity_id: alarm_control_panel.home_monitoring
      state: 'armed_night'
    
  action:
    - service: media_player.turn_off
      entity_id: media_player.bedroom_tv
