# Washing Machine - Activate when vibrations starts
- alias: '[ELECTRONIC] Washing Machine - Turn On'
  
  trigger:
    - platform: numeric_state
      entity_id: sensor.washing_machine_sensor_strength
      above: 100
        
  condition:
    - condition: state
      entity_id: input_boolean.washing_machine
      state: 'off'

  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.washing_machine
        
# Washing Machine - Deactivate and notify when finish
- alias: '[ELECTRONIC] Washing Machine - Turn Off'
  
  trigger:
    - platform: numeric_state
      entity_id: sensor.washing_machine_sensor_strength
      below: 100
        
  condition:
    - condition: state
      entity_id: input_boolean.washing_machine
      state: 'on'
      
  action:
    - service: notify.pushover
      data:
        message: Washing Machine sensor haven't been activated for 5 minutes.
        title: Washing Machine Finished
            
    - service: script.play_tts_group
      data:
        entities:
          - media_player.bedroom_clock
          - media_player.office_speaker
          - media_player.living_room_speaker
          - media_player.kitchen_display
        message: Washing Machine is Finish
        volume: |
          {% if states.alarm_control_panel.home_monitoring.state == 'disarmed' %}
            0.6
          {% elif states.alarm_control_panel.home_monitoring.state == 'armed_night' %}
            0.5
          {% else %}
            1
          {% endif %}
        
    - service: input_boolean.turn_off
      entity_id: input_boolean.washing_machine