# Active Mailbox Notification if strength is above 15
- alias: '[MAILBOX] Active Notification'
  
  trigger:
    - platform: numeric_state
      entity_id: sensor.mailbox_sensor_strength
      above: 15
      
  condition:
    - condition: state
      entity_id: input_boolean.mailbox
      state: 'off'
      
  action:
    - service: notify.pushover
      data:
        message: Mailbox Sensor got just triggered
        title: You have mail
            
    - service: media_player.play_media
      data:
        entity_id: group.notification_speakers
        media_content_id: https://lbrg.duckdns.org:8123/local/sounds/mailbox.wav
        media_content_type: music
        
    - service: input_boolean.turn_on
      entity_id: input_boolean.mailbox
        
# Deactive Mailbox Notification is strength drop below 15
- alias: '[MAILBOX] Deactivate Notification'

  trigger:
    - platform: numeric_state
      entity_id: sensor.mailbox_sensor_strength
      below: 15
      
  condition:
    - condition: state
      entity_id: input_boolean.mailbox
      state: 'on'
      
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.mailbox