# Active Mailbox Notification if vibration is detected
- alias: '[MAILBOX] Active Notification'
  
  trigger:
    - platform: state
      entity_id: sensor.mailbox_sensor_action
      to: 'vibration'
      
  condition:
    - condition: state
      entity_id: input_boolean.mailbox
      state: 'off'
      
  action:
    - service: notify.pushover
      data:
        message: Mailbox Sensor got just triggered
        title: You have mail
        
    - service: script.play_mp3_group
      data:
        entities:
          - media_player.bedroom_clock
          - media_player.office_speaker
          - media_player.living_room_speaker
          - media_player.kitchen_display
        file: /local/sounds/mailbox.wav
        volume: |
          {% if states.alarm_control_panel.home_monitoring.state == 'disarmed' %}
            0.6
          {% elif states.alarm_control_panel.home_monitoring.state == 'armed_night' %}
            0.1
          {% else %}
            0.1
          {% endif %}
        
    - service: input_boolean.turn_on
      entity_id: input_boolean.mailbox
        
# Deactive Mailbox Notification is strength drop below 15
- alias: '[MAILBOX] Deactivate Notification'

  trigger:
    - platform: numeric_state
      entity_id: sensor.mailbox_sensor_strength
      below: 15
      
  condition:
    - condition: state
      entity_id: input_boolean.mailbox
      state: 'on'
      
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.mailbox