# Turn on Bathroom Light when motion
- alias: '[LIGHTNING] Bathroom Light - Turn on when motion'

  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_motion_sensor_occupancy
      to: 'on'
  
  condition:
    - condition: state
      entity_id: light.bathroom_light
      state: 'off'
      
  action:
    - service: light.turn_on
      entity_id: light.bathroom_light
      
# Turn off Bathroom Light when low humidity and no motion
- alias: '[LIGHTNING] Bathroom Light - Turn off when no motion'

  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_motion_sensor_occupancy
      to: 'off'
      for:
        minutes: 5
        
    - platform: numeric_state
      entity_id: sensor.bathroom_temperature_humidity_sensor_humidity
      below: 75
        
  condition:
    - condition: state
      entity_id: light.bathroom_light
      state: 'on'
      
    - condition: state
      entity_id: binary_sensor.bathroom_motion_sensor_occupancy
      state: 'off'
      for:
        minutes: 5
    
    - condition: numeric_state
      entity_id: sensor.bathroom_temperature_humidity_sensor_humidity
      below: 75
      
  action:
    - service: light.turn_off
      entity_id: light.bathroom_light