# Turn on Hallway Light when motion
- alias: '[LIGHTNING] Hallway Light - Turn on when motion'

  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      no_motion_wait: '300'
      motion_entity: binary_sensor.hallway_motion_sensor_occupancy
      light_target:
        entity_id: light.hallway_light