# Turn on Hallway Light when motion (disarmed)
- alias: '[LIGHTNING] Hallway Light - Turn on when motion (disarmed)'

  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_motion_sensor_1_occupancy
      to: 'on'
      
    - platform: state
      entity_id: binary_sensor.hallway_motion_sensor_2_occupancy
      to: 'on'
      
  condition:
    - condition: state
      entity_id: light.hallway_light
      state: 'off'
      
    - condition: state
      entity_id: alarm_control_panel.home_monitoring
      state: 'disarmed'
      
  action:
    - service: light.turn_on
      entity_id: light.hallway_light
      
    - wait_for_trigger:
      - platform: state
        entity_id: binary_sensor.hallway_motion_sensor_1_occupancy
        to: 'off'
        for:
          seconds: 300
          
      - platform: state
        entity_id: binary_sensor.hallway_motion_sensor_2_occupancy
        to: 'off'
        for:
          seconds: 300
          
      timeout:
        minutes: 30
          
      continue_on_timeout: true
      
    - service: light.turn_off
      entity_id: light.hallway_light
    
# Turn on Hallway Light when motion (night)
- alias: '[LIGHTNING] Hallway Light - Turn on when motion (night)'

  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_motion_sensor_1_occupancy
      to: 'on'
      
    - platform: state
      entity_id: binary_sensor.hallway_motion_sensor_2_occupancy
      to: 'on'
      
  condition:
    - condition: state
      entity_id: light.hallway_light
      state: 'off'
      
    - condition: state
      entity_id: alarm_control_panel.home_monitoring
      state: 'armed_night'
      
    - condition: or
      conditions:
        - condition: state
          entity_id: light.bedroom_led_strips
          state: 'on'
          
        - condition: state
          entity_id: light.bedstand_lights
          state: 'on'
      
  action:
    - service: light.turn_on
      entity_id: light.hallway_light
      
    - wait_for_trigger:
      - platform: state
        entity_id: binary_sensor.hallway_motion_sensor_1_occupancy
        to: 'off'
        for:
          seconds: 120
          
      - platform: state
        entity_id: binary_sensor.hallway_motion_sensor_2_occupancy
        to: 'off'
        for:
          seconds: 120
          
      timeout:
        minutes: 15
        
      continue_on_timeout: true
      
    - service: light.turn_off
      entity_id: light.hallway_light