# Laundry Room Spots - Toggle based on sun and time
- alias: '[LIGHTNING] Laundry Room Spots - Toggle based on sun and time'

  trigger:
    - platform: time
      at: 05:30
      
    - platform: sun
      event: sunset
      offset: '-0:30'
      
    - platform: time
      at: 00:00
      
    - platform: sun
      event: sunrise
      offset: '+0:30'

  action:
    - service: |
        {% if trigger.platform == 'sun' %}
          {% if trigger.event == 'sunset' %}
            switch.turn_on
          {% else %}
            switch.turn_off
          {% endif %}
        {% else %}
          {% if trigger.now.hour == 0 %}
            switch.turn_off
          {% else %}
            switch.turn_on
          {% endif %}
        {% endif %}
      data:
        entity_id: switch.shelly1
      
# Front Door Light - Toggle based on sun and time
- alias: '[LIGHTNING] Front Door Light - Toggle based on sun and time'

  trigger:
    - platform: time
      at: 05:30
      
    - platform: sun
      event: sunset
      offset: '-0:30'
      
    - platform: time
      at: 00:00
      
    - platform: sun
      event: sunrise
      offset: '+0:30'

  action:
    - service: |
        {% if trigger.platform == 'sun' %}
          {% if trigger.event == 'sunset' %}
            light.turn_on
          {% else %}
            light.turn_off
          {% endif %}
        {% else %}
          {% if trigger.now.hour == 0 %}
            light.turn_off
          {% else %}
            light.turn_on
          {% endif %}
        {% endif %}
      data:
        entity_id: light.front_door_light
      
# Laundry Room Light - Turn on when door open
- alias: '[LIGHTNING] Laundry Room Light - Turn on when Front Door opens'

  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_contact_sensor_contact
      to: 'on'
      
  action:
    - service: light.turn_on
      entity_id: light.laundry_room_light
      
    - wait_for_trigger:
      - platform: state
        entity_id: binary_sensor.front_door_contact_sensor_contact
        to: 'off'
        for:
          minutes: 5
      timeout:
        minutes: 15
      continue_on_timeout: true
    
    - service: light.turn_off
      entity_id: light.laundry_room_light