# Living Room Spots - Toggle based on sun and presence
- alias: '[LIGHTNING] Living Room TV Spots - Toggle based on sun and location mode'

  trigger:
    - platform: sun
      event: sunset
      
    - platform: sun
      event: sunrise
      
    - platform: state
      entity_id: alarm_control_panel.home_monitoring

  action:
    - service: |
        {% if trigger.platform == 'sun' %}
          {% if trigger.event == 'sunset' %}
            {% if states.alarm_control_panel.home_monitoring.state == 'disarmed' %}
              light.turn_on
            {% else %}
              light.turn_off
            {% endif %}
          {% else %}
            light.turn_off
          {% endif %}
        {% else %}
          {% if trigger.to_state.state == 'disarmed' %}
            {% if states.sun.sun.state == 'below_horizon' %}
              light.turn_on
            {% else %}
              light.turn_off
            {% endif %}
          {% else %}
            light.turn_off
          {% endif %}
        {% endif %}
      data:
        entity_id: light.living_room_tv_spots