# Toilet Light - Turn on when door open
- alias: '[LIGHTNING] Toilet Light - Turn on when door opens'

  trigger:
    - platform: state
      entity_id: binary_sensor.toilet_door_sensor_contact
      to: 'on'
      
  action:
    - service: light.turn_on
      entity_id: light.toilet_light
      
    - wait_for_trigger:
      - platform: state
        entity_id: binary_sensor.toilet_door_sensor_contact
        to: 'off'
        for:
          minutes: 5
      timeout:
        minutes: 30
      continue_on_timeout: true
    
    - service: light.turn_off
      entity_id: light.toilet_light